name: CI
on: [pull_request]

jobs:
    
  build-integration:
    name: Integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout code
        uses: actions/checkout@master

      - name: run integration tests
        run: |
          mvn -B clean install -Pdocker -DskipTests
          mvn -f tests/pom.xml -DintegrationTests -DredirectTestOutputToFile=false